apiVersion: v1
kind: Service
metadata:
  name: jenkins-practice-app
  labels:
    app: jenkins-practice-app
spec:
  type: NodePort
  selector:
    app: jenkins-practice-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
    name: http