apiVersion: v1
kind: Service
metadata:
  name: jenkins-practice-service
  namespace: dev
  labels:
    app: jenkins-practice
spec:
  type: NodePort
  selector:
    app: jenkins-practice
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080